export  const elements = {
    slider: document.querySelectorAll('.slider-custom'),
    sliderContainer: document.querySelector('.slider'),
    dots: document.querySelectorAll('.dot'),
    sliderCharacter: document.querySelectorAll('.img-item-container'),
    heroes: document.querySelector('.img-item-container'),
    getCharactersLists : document.querySelector('.character-lists'),
    forLoader: document.querySelector('.for-loader'),
    comicsTrending: document.querySelector('.comics-trending'),
    infoCharacter: document.querySelector('.info-container'),
    comicCon: document.querySelector('.characters-comics-container'),
    comicInfo: document.querySelector(".comic-info-container"),
    searchText: document.querySelector(".search-text"),
    searchBox: document.getElementById("search-box"),
    searchCharacter: document.querySelector(".search-lists-character"),
};